name: Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test Rust ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v4
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: ${{ matrix.rust }}

    - name: Run tests
      run: cargo test --verbose

  rustfmt:
    name: Ensure rustfmt is happy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hecrj/setup-rust-action@v2
      with:
        components: rustfmt
    - run: cargo fmt --all -- --check

  clippy:
    name: Lint the codebase with clippy
    runs-on: ubuntu-latest
    # env:
    #   RUSTFLAGS: -Dwarnings
    steps:
    - uses: actions/checkout@v4
    - uses: hecrj/setup-rust-action@v2
      with:
        components: clippy
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --all-features --examples --tests

  rustdoc-links:
    name: Check doc links are valid
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: nightly
    - run: cargo rustdoc --all-features
